# stt_license_harden_shared_library(<target> [EXPORTS <pattern>...])
#
# 공유 라이브러리(예: SDK의 JNI .so)에서 JNI 진입점만 외부에 공개하고 나머지 심볼은 모두 숨긴다.
#   - 정적 링크된 OpenSSL 의 EVP_DigestVerify 등이 export 되어 있으면 LD_PRELOAD 로 검증을 가로챌 수 있다.
#     (scripts/check.sh 6단계에서 실측: 숨기지 않은 빌드는 변조 라이선스가 통과)
#   - 기본 공개 대상: Java_*, JNI_OnLoad, JNI_OnUnload. C API 등을 더 공개하려면 EXPORTS 로 패턴을 추가한다.
#
# 적용 방식: 링커 버전 스크립트(local: *) + --exclude-libs,ALL. GNU ld / gold / lld (ELF, Linux) 전용.
function(stt_license_harden_shared_library target)
  cmake_parse_arguments(ARG "" "" "EXPORTS" ${ARGN})
  if(ARG_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "stt_license_harden_shared_library: unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if(NOT TARGET ${target})
    message(FATAL_ERROR "stt_license_harden_shared_library: '${target}' is not a target")
  endif()
  get_target_property(_type ${target} TYPE)
  if(NOT _type STREQUAL "SHARED_LIBRARY" AND NOT _type STREQUAL "MODULE_LIBRARY")
    message(FATAL_ERROR "stt_license_harden_shared_library: '${target}' must be a SHARED or MODULE library (is ${_type})")
  endif()
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(WARNING "stt_license_harden_shared_library: only supported on Linux/ELF; '${target}' left unchanged")
    return()
  endif()

  set(_content "/* generated by stt_license_harden_shared_library() */\n{\n  global:\n")
  foreach(_p Java_* JNI_OnLoad JNI_OnUnload ${ARG_EXPORTS})
    string(APPEND _content "    ${_p};\n")
  endforeach()
  string(APPEND _content "  local:\n    *;\n};\n")
  set(_map "${CMAKE_CURRENT_BINARY_DIR}/${target}.exports.map")
  # file(GENERATE)는 내용이 같으면 파일을 다시 쓰지 않는다 → 불필요한 재링크 없음
  file(GENERATE OUTPUT "${_map}" CONTENT "${_content}")

  target_link_options(${target} PRIVATE
    "LINKER:--exclude-libs,ALL"
    "LINKER:--version-script=${_map}")
  set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_map}")
endfunction()
